
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: deploy
  password: deploy
  host: 127.0.0.1

development:
  <<: *default
  database: airtrys_development



test:
  <<: *default
  database: airtrys_test


production:
  <<: *default
  database: airtrys_production
  username: deploy
  password: <%= ENV['BOOKS_DATABASE_PASSWORD'] %>






